
version: "3.8"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - data:/data/db
    ports:
      - "8080:8080"
    networks:
      - default-network
   
  
volumes:
  data:   

networks:
  default-network:
    driver: bridge
