version: 2.1

jobs:
  build:
    docker:
      - image: "circleci/python:3.10-node-browsers-legacy"
    steps:
      - checkout 
      - run: echo "this is the build job"
          
  test:
    docker:
      - image: "circleci/python:3.10-node-browsers-legacy"
    steps:
      - run: echo "this is the test job"  

workflows:
  build_and_test:
    jobs:
      - build
      - test