version: 2.1

jobs:
  build:
    docker:
      - image: "circleci/python:3.10-node-browsers-legacy"
    steps:
      - checkout
      - run: 
          name: install_dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
  test:
    docker:
      - image: "circleci/python:3.10-node-browsers-legacy"
    steps:
      - checkout
      - run: 
        name: run testes
        command: |
            . venv/bin/activate
            pytest -v --cov=toyrobo


workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build